export default {
    intro:{
        "card1":[
            require("../../assets/images/content/skin_cancer.png"),
            require("../../assets/images/content/body_virus.png"),
            require("../../assets/images/content/naizou_woman_bad.png"),
            require("../../assets/images/content/saibou_gan_cancer.png")
        ],
        "card2":[
            require("../../assets/images/content/statistics_graph.png"),
            require("../../assets/images/content/graph01_circle.png"),
            require("../../assets/images/content/doctor_monshin2.png"),
            require("../../assets/images/content/osyougatsu_text_2024.png"),
            require("../../assets/images/content/iryou_karute_carte.png"),
            require("../../assets/images/content/ohaka_bochi_seiyou.png")

        ],
        "card3":[
            require("../../assets/images/content/search_mushimegane.png"),
            require("../../assets/images/content/melanoma_on_hand.png"),
            require("../../assets/images/content/magnifier1_doctor.png"),
            require("../../assets/images/content/abcde.png"),
            require("../../assets/images/content/abcde_a.png"),
            require("../../assets/images/content/abcde_b.png"),
            require("../../assets/images/content/abcde_c.png"),
            require("../../assets/images/content/abcde_d.png"),
            require("../../assets/images/content/abcde_e.png")
        ],
        "card4":[
            require("../../assets/images/content/mark_chuui.png"),
            require("../../assets/images/content/pop_chuui.png"),
            require("../../assets/images/content/necchuusyou_taoreru_boy.png"),
            require("../../assets/images/content/skin_cancer.png"),
            require("../../assets/images/content/book.png"),
            require("../../assets/images/content/meneki_bad.png"),
            require("../../assets/images/content/kaigo_rourou_easy.png")
        ]
    }
}